tiziano_local:
  paths:
    src_path: "/Users/tizianocausin/Desktop/project1917-26/python_scripts/src"
    data_dir: "/Volumes/LivingstoneLab"


tiziano_mac_mini:
  paths:
    src_path: "/Users/tizianocausin/Desktop/project1917-26/python_scripts/src"
    data_dir: "/Users/tizianocausin/1917_local"



subjects: [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 25, 28, 30, 31, 34]
